version: '3.8'

services:
  app:
    container_name: evolution-dashboard
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: evolution-dashboard:1.5.0
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    # Sem volumes - banco SQLite será recriado a cada restart
    # Seed do admin executado automaticamente com credenciais do .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - evolution-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  evolution-network:
    driver: bridge
