services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # Persistir banco de dados SQLite
      - sqlite_data:/app/prisma
    restart: unless-stopped

volumes:
  sqlite_data:
